# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-demo-k',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/nbdev-demo-k',
                'lib_path': 'nbdev_demo_k'},
  'syms': {'nbdev_demo_k.core': {'nbdev_demo_k.core.foo': ('core.html#foo', 'nbdev_demo_k/core.py')}}}